#!/bin/bash
# Simple deployment script for standalone Juice Shop

echo "=================================="
echo "Deploying Standalone Juice Shop"
echo "=================================="
echo ""
echo "This will install Juice Shop on port 4000"
echo "Access will be via: http://155.138.197.128:4000"
echo ""
echo "Steps:"
echo "1. Copy install script to server"
echo "2. SSH to server and run installation"
echo ""
echo "Manual steps needed:"
echo ""
echo "Step 1: Copy the script"
echo "scp /Users/walterbarr_1/sql-injection-lab/install_standalone_juice.sh root@155.138.197.128:/tmp/"
echo ""
echo "Step 2: SSH and run installation"
echo "ssh root@155.138.197.128"
echo "bash /tmp/install_standalone_juice.sh"
echo ""
echo "Step 3: Test access"
echo "Open browser to: http://155.138.197.128:4000"
echo ""
echo "The password is: \$Hg5sD&8Lp@9"